###Single Layer Perceptron (SLP).

In [2]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

### 1. Load the data

In [3]:
X = np.array(
    [[7,1],
    [5, -4],
    [-3, -2],
    [-2, 2]]
            )

In [4]:
X

array([[ 7,  1],
       [ 5, -4],
       [-3, -2],
       [-2,  2]])

In [5]:
Y = np.array([1,0,0,1])
Y

array([1, 0, 0, 1])

### 2. Define the `activation function`

- `unit step` activation function

In [6]:
def step_af(z):
    return 1 if z>=0 else 0

### 3. Define `Single Layer Perceptron Model`

In [7]:
### 3.a. Compute Cost
def compute_cost(X,Y,W,b):
    '''
    X: Input Array
    Y: Target (Y labels)
    W: Weight Array
    b: bias
    '''
    total_errors = 0 # how many misclassifications have happened

    for i in range(len(X)):
        z = np.dot(W, X[i]) + b # weighted sum of inputs + bias --> one row at a time
        y_pred = step_af(z) # predicted value using unit step activation function

        if y_pred != Y[i]: # comparing predicted Y against actual Y
            total_errors += 1 #counting the instances of error
    return total_errors

#### 3.b. Let us create the SLP train

def slp_train(X, Y, W, b, alpha, epochs):
    ### Create the couple of empty lists to track historical updates
    errors_per_epoch = []
    accuracy_per_epoch = []

    ### Suppress scientific notation and control decimals
    np.set_printoptions(precision = 2, suppress = True)

    for epoch in range(epochs): # outer for loop
        print(f"\nEpoch# {epoch + 1}")

        total_errors = 0 # instances of mis-classification
        correct = 0 #instances of correct classification

        for i in range(len(X)): # inner for loop
            x = X[i] # picking a row - one at a time
            y = Y[i] # picking the target label for that specific row -- actual Y
            z = np.dot(W,x) + b # weighted sum of inputs + bias
            y_pred = step_af(z) # predicted Y
            error = y_pred - y # calculate error

            if error != 0:
                ### Since there is an error, need to update weights & biases
                W = W - (alpha * (error * x))
                b = b - (alpha * error)
                total_errors += 1
            else:
                correct += 1
            cost = compute_cost(X, Y, W, b)
            # Well-formatted log output
            print(f"{'Input:':<10} {x}  "
                  f"{'Prediction:':<12} {y_pred}  "
                  f"{'Actual:':<8} {y}  "
                  f"{'Error:':<7} {error}  "
                  f"{'Weights:':<9} {W}  "
                  f"{'Bias:':<6} {b:.3f}  "
                  f"{'Cost:':<6} {cost}")

        errors_per_epoch.append(total_errors) #appending the historical errors
        accuracy_per_epoch.append(correct/len(X)) #appending the avg. correct instances

    return W, b, errors_per_epoch, accuracy_per_epoch

In [8]:
Y

array([1, 0, 0, 1])

In [9]:
W = np.array([0.5, -0.5]) #weights are as many as number of X features--> number of input variables
b = 0.1
alpha = 0.1
epochs = 10

#### `Let us try running with `SLP` with `initial weights and biases` set by modeler

In [10]:
W = np.array([0.5, -0.5]) #weights are as many as number of X features--> number of input variables
b = 0.1
alpha = 0.1 #standard learning rate
epochs = 10 #number of epochs

In [11]:
final_W, final_b, errors, accuracy = slp_train(X, Y, W, b, alpha, epochs=10)


Epoch# 1
Input:     [7 1]  Prediction:  1  Actual:  1  Error:  0  Weights:  [ 0.5 -0.5]  Bias:  0.100  Cost:  2
Input:     [ 5 -4]  Prediction:  1  Actual:  0  Error:  1  Weights:  [ 0.  -0.1]  Bias:  0.000  Cost:  4
Input:     [-3 -2]  Prediction:  1  Actual:  0  Error:  1  Weights:  [0.3 0.1]  Bias:  -0.100  Cost:  2
Input:     [-2  2]  Prediction:  0  Actual:  1  Error:  -1  Weights:  [0.1 0.3]  Bias:  0.000  Cost:  0

Epoch# 2
Input:     [7 1]  Prediction:  1  Actual:  1  Error:  0  Weights:  [0.1 0.3]  Bias:  0.000  Cost:  0
Input:     [ 5 -4]  Prediction:  0  Actual:  0  Error:  0  Weights:  [0.1 0.3]  Bias:  0.000  Cost:  0
Input:     [-3 -2]  Prediction:  0  Actual:  0  Error:  0  Weights:  [0.1 0.3]  Bias:  0.000  Cost:  0
Input:     [-2  2]  Prediction:  1  Actual:  1  Error:  0  Weights:  [0.1 0.3]  Bias:  0.000  Cost:  0

Epoch# 3
Input:     [7 1]  Prediction:  1  Actual:  1  Error:  0  Weights:  [0.1 0.3]  Bias:  0.000  Cost:  0
Input:     [ 5 -4]  Prediction:  0  Actual: